"""Derives the Uthmani-rasm → simple-spelling table used by `norm-v2` search text.

The table is not written by hand: it comes from aligning Tanzil's Uthmani and
simple texts word by word (ayat with the same number of words), keeping only
spellings that never occur in the simple text and map to one simple form at
least 95% of the time. It changes search text only, never displayed text.
"""
from collections import Counter, defaultdict
from pathlib import Path

from ..rag import normalize

MIN_COUNT = 2
MIN_SHARE = 0.95
HEADER = ("# Uthmani rasm -> simple spelling, for search text only (norm-v2).\n"
          "# Derived from Tanzil Quran Text (Uthmani and Simple), (C) Tanzil Project, CC BY 3.0, tanzil.net.\n"
          "# Generated by scripts/fetch_sources.py; do not edit by hand.\n")


def derive(uthmani: dict, simple: dict) -> tuple[dict[str, str], dict]:
    pairs: dict[str, Counter] = defaultdict(Counter)
    vocabulary: Counter = Counter()
    aligned = total = before = 0
    tokens = {key: (normalize.tokens_v1(uthmani[key]), normalize.tokens_v1(simple[key])) for key in uthmani}
    for left, right in tokens.values():
        vocabulary.update(right)
    for left, right in tokens.values():
        if len(left) != len(right):
            continue
        aligned += 1
        for word, target in zip(left, right):
            total += 1
            before += word == target
            if word != target:
                pairs[word][target] += 1
    table = {}
    for word, targets in pairs.items():
        target, count = targets.most_common(1)[0]
        if count >= MIN_COUNT and count / sum(targets.values()) >= MIN_SHARE and not vocabulary[word]:
            table[word] = target
    after = sum(table.get(word, word) == target for left, right in tokens.values() if len(left) == len(right)
                for word, target in zip(left, right))
    return dict(sorted(table.items())), {"aligned_ayat": aligned, "aligned_words": total, "entries": len(table),
                                          "agreement_before": round(before / total, 4),
                                          "agreement_after": round(after / total, 4)}


def render(table: dict[str, str]) -> str:
    return HEADER + "".join(f"{word}\t{target}\n" for word, target in table.items())


def write_if_changed(path: Path, table: dict[str, str]) -> bool:
    text = render(table)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8", newline="\n")
    return True
