"""Build the corpus knowledge graph (kg-v1) and its review report (doc/knowledge-graph.md).

    python scripts/build_graph.py

Needs fetch_sources.py and build_corpus.py first. Writes corpus/graph/ (nodes.jsonl, edges.jsonl,
unresolved.jsonl, summary.json; not in git, rebuilt from the corpus) and, for review in git,
corpus/reports/knowledge_graph.md and corpus/reports/knowledge_graph_prophets.json. The graph holds ids,
references and counts only; scripts/graph_query.py shows the text behind them from the local canonical files.
"""
from collections import defaultdict
import json
import sys
import time

import _common  # noqa: F401
from _common import ROOT
from companion_api.corpusprep.segments import load_metadata
from companion_api.knowledge import graph as kg

CORPUS = ROOT / "corpus"
OUT = CORPUS / "graph"
REPORT = CORPUS / "reports/knowledge_graph.md"
PROPHETS = CORPUS / "reports/knowledge_graph_prophets.json"


def _ranges(refs: list[str]) -> list[str]:
    """quran:S:A references collapsed into S:A-B runs."""
    keys = sorted({tuple(int(x) for x in ref.split(":")[1:]) for ref in refs})
    runs, start, previous = [], None, None
    for key in keys:
        if previous and key[0] == previous[0] and key[1] == previous[1] + 1:
            previous = key
            continue
        if start:
            runs.append(f"{start[0]}:{start[1]}" + (f"-{previous[1]}" if previous != start else ""))
        start = previous = key
    if start:
        runs.append(f"{start[0]}:{start[1]}" + (f"-{previous[1]}" if previous != start else ""))
    return runs


def prophet_index(graph: kg.Graph) -> dict:
    index = defaultdict(lambda: {"story_ayat": [], "ayat_naming": [], "tafsir_explaining_story": set(),
                                 "tafsir_naming": [], "hadith_naming": []})
    explains = defaultdict(set)
    for edge in graph.edges.values():
        if edge["type"] == "EXPLAINS":
            explains[edge["target"]].add(edge["source"])
    for edge in graph.edges.values():
        if edge["type"] == "STORY_IN":
            entry = index[edge["source"]]
            entry["story_ayat"].append(edge["target"])
            entry["tafsir_explaining_story"] |= explains[edge["target"]]
        elif edge["type"] == "MENTIONS_PROPHET":
            kind = graph.nodes.get(edge["source"], {}).get("type")
            key = {"ayah": "ayat_naming", "tafsir_section": "tafsir_naming", "hadith": "hadith_naming"}.get(kind)
            if key:
                index[edge["target"]][key].append(edge["source"])
    out = {}
    for prophet in sorted(node for node, data in graph.nodes.items() if data["type"] == "prophet"):
        entry = index[prophet]
        out[prophet] = {"name_ar": graph.nodes[prophet].get("name_ar"),
                        "story_ayat": _ranges(entry["story_ayat"]), "ayat_naming": _ranges(entry["ayat_naming"]),
                        "tafsir_explaining_story": sorted(entry["tafsir_explaining_story"]),
                        "tafsir_naming": sorted(entry["tafsir_naming"]),
                        "hadith_naming": sorted(entry["hadith_naming"])}
    return out


def report(summary: dict, prophets: dict, graph: kg.Graph) -> str:
    lines = ["# Knowledge graph (kg-v1) — review report", "",
             "Generated by `scripts/build_graph.py`; do not edit by hand. A draft index for reviewers built from "
             "candidate and pending-legal sources: nothing in it is reviewed. Ids and counts only; "
             "`python scripts/graph_query.py ...` shows the text behind an id from the local canonical files.", "",
             f"Inputs sha256 `{summary['inputs_sha256']}`.", "", "## Nodes", "", "| Type | Count |", "| --- | ---: |"]
    lines += [f"| {kind} | {count:,} |" for kind, count in summary["nodes"].items()]
    lines += ["", "## Edges by how they were found", "", "| Edge | Method | Status | Count |",
              "| --- | --- | --- | ---: |"]
    for key, count in summary["edges_by_method_status"].items():
        kind, method, status = key.split(":")
        lines.append(f"| {kind} | {method} | {status} | {count:,} |")
    cited = summary["editor_citations"]
    lines += ["", "## The editor's hadith citations", "",
              f"- Bukhari citations in the editor's notes linked to a hadith: **{cited['bukhari_linked']:,}**; "
              f"confirmed by shared text: **{cited['bukhari_text_confirmed']:,}**; also found by text matching "
              f"alone: **{cited['bukhari_also_found_by_text']:,}**.",
              f"- Muslim citations linked through the text of the same section: **{cited['muslim_linked_through_text']:,}**.",
              "- Not linked: " + ", ".join(f"{reason}: {count:,}" for reason, count in cited["unresolved"].items())
              + ". The editor numbers Sahih Muslim by Abdul-Baqi; the canonical collection uses sunnah.com numbering, "
              "so those citations are listed in `corpus/graph/unresolved.jsonl` until a number mapping exists.", "",
              "## Prophets", "",
              "| Prophet | Story ayat (source maps) | Ayat naming | Tafsir sections explaining the story | "
              "Tafsir sections naming | Hadith naming |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for prophet, data in prophets.items():
        story = summary["per_prophet"][prophet]["story_ayat"]
        lines.append(f"| {prophet.split(':')[1]} ({data['name_ar']}) | {story} | "
                     f"{summary['per_prophet'][prophet]['ayat_naming']} | {len(data['tafsir_explaining_story'])} | "
                     f"{summary['per_prophet'][prophet]['tafsir_sections_naming']} | "
                     f"{summary['per_prophet'][prophet]['hadith_naming']} |")
    lines += ["", "## What a reviewer should check first", "",
              "1. `STORY_IN` comes from the source maps under review (`doc/decisions/04-content-review.md`).",
              "2. `MENTIONS_PROPHET` from hadith: names after narrator words or before بن are skipped as narrators, "
              "but a name used for a companion or a later person can still slip through.",
              "3. `QUOTES_AYAH` and `CITES_HADITH` by text are n-gram matches: a shared formula can link the wrong "
              "ayah or hadith. `coverage` says how much of the ayah or hadith was found.",
              "4. Ambiguous names (هود، صالح، يحيى، أحمد) are linked only with a context word; check the misses.", ""]
    return "\n".join(lines)


def main() -> int:
    started = time.monotonic()
    metadata = next((CORPUS / "raw/tanzil-quran-metadata").glob("*.xml"), None)
    names = load_metadata(metadata)[0] if metadata else None
    graph = kg.build(CORPUS, names)
    summary = kg.write(graph, OUT, inputs_sha256=kg.inputs_digest(CORPUS))
    prophets = prophet_index(graph)
    PROPHETS.write_text(json.dumps({"graph_version": kg.GRAPH_VERSION, "inputs_sha256": summary["inputs_sha256"],
                                    "prophets": prophets}, ensure_ascii=False, indent=1) + "\n",
                        encoding="utf-8", newline="\n")
    REPORT.write_text(report(summary, prophets, graph), encoding="utf-8", newline="\n")
    print(json.dumps({"nodes": summary["nodes"], "edges": summary["edges"],
                      "editor_citations": summary["editor_citations"],
                      "seconds": round(time.monotonic() - started, 1)}, ensure_ascii=False, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
